Zones 0711
akgunjal/block-volume-attacher pull request #7
Opened 2018-07-12 04:51 UTC by jsilberm

2018-07-12 04:51 UTC, jsilberm commented
Please take this one, and I'll close out the PR for the 'delete cluster' instructions. 
Thanks.

2018-07-12 06:03 UTC, akgunjal requested changes

2018-07-12 06:03 UTC, akgunjal commented on portworx/README.md
> +     curl https://install.portworx.com/px-wipe | bash
As per my discussion with Sen yesterday, he said we should execute this curl command to wipe out first without deleting the Portworx daemon set. Else the wipe out will not happen. Also this curl will do wipe-out and also delete all kubernetes resources of Portworx so technically we don't need helm delete. Or users can do helm delete after curl which means basically nothing is there is delete at that point.

2018-07-13 18:22 UTC, jsilberm commented
Ping?

2018-07-14 06:39 UTC, akgunjal approved these changes

2018-07-14 06:39 UTC, merged